language: cpp

matrix:

  include:

    - os: linux
      dist: trusty
      sudo: required
      env: VERGE_PLATFORM='linux'
      compiler: gcc

    - os: linux
      dist: trusty
      sudo: required
      env: VERGE_PLATFORM='windows'
      compiler: gcc

    - os: osx
      osx_image: xcode7.2
      env: VERGE_PLATFORM='mac'
      compiler: clang 

before_install:
  - ./building/${VERGE_PLATFORM}/requirements.sh

install:
  - source ./building/${VERGE_PLATFORM}/build.sh

script:
  - echo "nothing."
