language: cpp

matrix:

  include:

    - os: linux
      dist: trusty
      sudo: required
      env: VERGE_PLATFORM='linux'
      compiler: gcc
      file: 'release_linux.zip'

    - os: linux
      dist: trusty
      sudo: required
      env: VERGE_PLATFORM='windows'
      compiler: gcc
      file: 'release_windows.zip'

    - os: osx
      osx_image: xcode7.2
      env: VERGE_PLATFORM='mac'
      compiler: clang 
      file: 'release_mac.zip'

before_install:
  - ./building/common.sh
  - ./building/${VERGE_PLATFORM}/requirements.sh

install:
  - ./building/${VERGE_PLATFORM}/build.sh

script:
  - ./building/${VERGE_PLATFORM}/dist.sh

deploy: 
  provider: releases
  api_key:
    secure: "2MFTd9bXbZlwLMh+/KkJWrUA5KKeGrpZCw/5iybkzPFhUYv2znskQia0XHnj5VIDNCC7a+CtmIz07ZEI7B3uB+UISCgpZ8ifmPGfGeuy0VI2qt+CZ0Z34oMsJNUkCFYLgGbi0/ro2lKL7BmSxClVHtfYgyxo/yLeTO9f7Q08CKPmb5Nv4EKycZq6rzA02UScRjiIHWfKZ6fDsCecV6CYJSoKsuOfw54/1HBzh/iFtywQCjCrBOQwpPI11kO6GbrcTfYqz1c4Va6QVuDtH7yzW1VqEZHHnPDb6H+YEofVRhJAw3jHyisU/r6I3mnV1KaPkNW0iifRaQrFBYv9RWBhBuRJNGh1QwcTHhrDKxkF4IHBMbFjeeHrm07RTMT9Yp8tZbpF9Mc3KdMQBwOQhXWB7KvMYdcFpEKm5dfwcWqEl//YWBMvKf0EE7/vnTWDkEq7vn8ompRxqlPiLgkK2bqRtHrYFo5dtrY5BIDr7CCkL1XAiUCCZ2B5lezOwOzea/thUL+q2M8rELKjrXUFHehcIqRqs9JRXaiig10BKRKYlp+R/Sw/GFvh5xr0ALtV6rCzkfJlMdXqO3TXxQf/ZAV95tIafBEoBlQENqutMMDpNM2vrNrl6MIV1PNIfRREw5HSLJUmtP1H130EmhOX9PHZhGqZPIi1aRd6j0kXIwFURyw="
  skip_cleanup: true
  on:
    # TODO: change me vergeDEV
    repo: mkinney/VERGE
    tags: true
    all_branches: true

