language: cpp
sudo: required

env:
  matrix:
    - VERGE_PLATFORM='linux64'
    #- VERGE_PLATFORM='windows32' TODO after 64 works
    - VERGE_PLATFORM='windows64'

compiler:
- gcc

before_install:
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo add-apt-repository --yes ppa:bitcoin/bitcoin
  - sudo apt-get update -qq
  - VERGE_TARGET="${VERGE_PLATFORM::${#VERGE_PLATFORM}-2}"
  - sudo ./building/${VERGE_TARGET}/requirements.sh

install:
  - sudo source ./building/${VERGE_TARGET}/build.sh

script:
  - echo "nothing."
