language: cpp
compiler:
- gcc
before_install:
- sudo apt-get update -qq
- sudo apt-get install libboost1.48-all-dev build-essential pkg-config libtool autotools-dev autoconf automake libssl-dev libminiupnpc-dev libdb++-dev libdb-dev qt4-qmake libqt4-dev libssl-dev git
install:
- cd src
script:
- make -f makefile.unix USE_UPNP:=-
- cd ..
irc:
channels:
- "chat.freenode.net#verge"
template:
- "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
- "Alt Message : %{repository_slug} - (%{commit} - %{author}): %{message}, Build Time: %{duration}"
- "Change view : %{compare_url}"
- "Build details : %{build_url}"
