version: 2

defaults: &defaults
  machine:
      image: ubuntu-2204:2022.10.1

defaults-docker: &defaults-docker
  docker:
    - image: circleci/buildpack-deps:bionic

run_apt_packages: &run_apt_packages
  name: Prepare VM
  command: sudo apt-get update --fix-missing && sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common git python3.5 bison byacc python2

set_python_version: &set_python_version
  name: Set Python Version
  command: pyenv global 3.10.6

run_base_setup: &run_base_setup
  name: Setup repo and execute VM builder
  command: ./gitian-build.py --docker --commit --setup ${CIRCLE_PROJECT_USERNAME} ${CIRCLE_BRANCH:-${CIRCLE_TAG:-master}}

semvers: &semvers /v(?<=^[Vv]|^)(?:(?<major>(?:0|[1-9](?:(?:0|[1-9])+)*))[.](?<minor>(?:0|[1-9](?:(?:0|[1-9])+)*))[.](?<patch>(?:0|[1-9](?:(?:0|[1-9])+)*))(?:-(?<prerelease>(?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:0|[1-9](?:(?:0|[1-9])+)*))(?:[.](?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:0|[1-9](?:(?:0|[1-9])+)*)))*))?(?:[+](?<build>(?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:(?:0|[1-9])+))(?:[.](?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:(?:0|[1-9])+)))*))?)$/

jobs:
  release-prepare-machine:
    <<: *defaults
    steps:
      - run:
          <<: *run_apt_packages
      - checkout:
          path: ~/project/verge
      - run:
          name: Hardcopy gitian build script
          command: cp ./verge/contrib/gitian-build.py . && chmod u+x gitian-build.py
      - run:
          name: Prepare VM Builder
          command: git clone https://github.com/newroco/vmbuilder.git && cd vmbuilder && sudo chmod u+x ./setup.py && sudo python2 ./setup.py install 
      - persist_to_workspace:
          root: '.'
          paths:
            - '.'

  release-windows:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          <<: *run_apt_packages
      - run:
          <<: *set_python_version
      - run:
          <<: *run_base_setup
      - run:
          name: Gitian Build Windows
          command: ./gitian-build.py --docker --detach-sign -o w --commit -j 4 -m 4000 -b {CIRCLE_PROJECT_USERNAME} ${CIRCLE_BRANCH:-${CIRCLE_TAG:-master}}
      - run:
          name: Collect binaries
          command: mv verge-binaries/${CIRCLE_BRANCH:-${CIRCLE_TAG:-master}}/ bin
      - persist_to_workspace:
          root: .
          paths: ['bin']

  release-macos:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          <<: *run_apt_packages
      - run:
          <<: *set_python_version
      - run:
          <<: *run_base_setup
      - run:
          name: Add OSX SDK
          command: mkdir -p gitian-builder && cd ./gitian-builder && mkdir -p inputs && cd inputs && curl -L https://github.com/phracker/MacOSX-SDKs/releases/download/10.13/MacOSX10.11.sdk.tar.xz --output MacOSX10.11.sdk.tar.gz
      - run:
          name: Gitian Build MacOS
          command: ./gitian-build.py --docker --detach-sign -o m --commit -j 4 -m 4000 -b {CIRCLE_PROJECT_USERNAME} ${CIRCLE_BRANCH:-${CIRCLE_TAG:-master}}
      - run:
          name: Collect binaries
          command: mv verge-binaries/${CIRCLE_BRANCH:-${CIRCLE_TAG:-master}}/ bin
      - persist_to_workspace:
          root: .
          paths: ['bin']

  release-linux:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          <<: *run_apt_packages
      - run:
          <<: *set_python_version
      - run:
          <<: *run_base_setup
      - run:
          name: Gitian Build Linux
          command: ./gitian-build.py --docker --detach-sign -o l --commit -j 4 -m 4000 -b ${CIRCLE_PROJECT_USERNAME} ${CIRCLE_BRANCH:-${CIRCLE_TAG:-master}}
      - run:
          name: Collect binaries
          command: mv verge-binaries/${CIRCLE_BRANCH:-${CIRCLE_TAG:-master}}/ bin
      - persist_to_workspace:
          root: .
          paths: ['bin']

  upload-github-releases:
    docker:
      - image: circleci/buildpack-deps:bionic
    steps:
      - checkout
      - attach_workspace:
          at: ./bin
      - run:
          name: Install gpg
          command: sudo apt-get install gnupg
      - run:
          name: Install GHR
          command: export GHR_VERSION=0.13.0 && export ENV GHR_URL=https://github.com/tcnksm/ghr/releases/download/v${GHR_VERSION}/ghr_v${GHR_VERSION}_linux_amd64.tar.gz && wget "$GHR_URL" && tar xzf ghr_v${GHR_VERSION}_linux_amd64.tar.gz && sudo mv ghr_v${GHR_VERSION}_linux_amd64/ghr /usr/bin/ghr && rm -r ghr_v${GHR_VERSION}_linux_amd64.tar.gz ghr_v${GHR_VERSION}_linux_amd64/
      - run:
          name: Add release private key
          command: echo -e $GPG_KEY > PRIVATE_GPG_KEY.asc && gpg --batch --import PRIVATE_GPG_KEY.asc
      - run:
          name: Generate SHA256 hashes & Sign release hashes
          command: cd ./bin/bin/ && shasum -a 256 verge-* > release.sha256sum && gpg --pinentry-mode loopback --clearsign --passphrase $GPG_PASSPHRASE --output release.sha256sum.sig --sign release.sha256sum
      - run:
          name: Prepare release body text
          command: |
            echo -e "## Release (${CIRCLE_TAG})\n\n### Requirements:\n\n---\n\n### Release notes:\n\n### Release Hashes and Signature\n\n\`\`\`gpg" > release.md
            cat ./bin/bin/release.sha256sum.sig >> release.md
            echo -e "\`\`\`\n\nSigned by public key \`7028 B24D 2265 AA27 6664  B078 BA2F 0EF9 9AF2 355B\` (<marpme@users.noreply.github.com>)" >> release.md
      - run:
          name: 'Publish Release on GitHub'
          command: |
            VERSION=$(git describe)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -n ${CIRCLE_TAG} -b "$(cat ./release.md)" -delete -draft ${CIRCLE_TAG} ./bin/bin/

  bionic-test-setup-env:
    docker:
      - image: circleci/buildpack-deps:bionic
    steps:
      - checkout
      - run:
          name: Hash dependencies
          command: md5sum depends/packages/* > hashes.run
      - restore_cache:
          key: bionic-source-depends-{{ checksum "./hashes.run" }}
          paths:
            - './depends'
      - run:
          name: Install dependencies
          command: sudo apt-get update && sudo apt-get install build-essential bison byacc libtool libboost-system-dev libboost-all-dev autotools-dev automake pkg-config bsdmainutils libattr1-dev make automake cmake curl g++-multilib binutils-gold python3
      - run:
          name: Creating depends
          command: cd depends/ && make -j4 HOST=x86_64-linux-gnu
      - save_cache:
          key: bionic-source-depends-{{ checksum "./hashes.run" }}
          paths:
            - './depends'
      - persist_to_workspace:
          root: '.'
          paths:
            - '.'

  bionic-test-create-and-test-build:
    docker:
      - image: circleci/buildpack-deps:bionic
    steps:
      - attach_workspace:
          at: '.'
      - run:
          name: Aptitude update and upgrade
          command: sudo apt update -y && sudo apt upgrade -y
      - run:
          name: Install dependencies
          command: sudo apt-get install build-essential byacc bison libboost-system-dev libboost-all-dev libtool autotools-dev automake pkg-config bsdmainutils python3 python3-dev libattr1-dev lcov
      - run:
          name: Force boost 1.77.0
          command: https://boostorg.jfrog.io/artifactory/main/release/1.77.0/source/boost_1_77_0.tar.gz && tar -xzf boost_1_77_0.tar.gz && cd boost_1_77_0 && ./bootstrap.sh --prefix=/usr/ && ./b2 install --prefix=/usr/local
      - run:
          name: Autogen tools
          command: ./autogen.sh 
      - run:
          name: Configuring code
          command: ./configure --enable-lcov --disable-bench --disable-dependency-tracking --disable-werror --prefix=`pwd`/depends/x86_64-linux-gnu --bindir=`pwd`/release/bin --libdir=`pwd`/release/lib
      - run:
          name: Make
          command: make -j4
      - run:
          name: Check binaries
          command: make -j4 check
      - run:
          name: Generate Coverage
          command: make -j4 test_verge_filtered.info
      - run:
          name: Upload code coverage
          command: bash <(curl -s https://codecov.io/bash) -f test_verge_filtered.info || (echo "Could not upload coverage report to codecov"; exit 1)

workflows:
  version: 2

  release:
    jobs:
      - release-prepare-machine:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - release-windows:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - release-prepare-machine
      - release-macos:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - release-prepare-machine
      - release-linux:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - release-prepare-machine
      - upload-github-releases:
          context: github-gangster
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - release-windows
            - release-macos
            - release-linux

  bionic-linux-testing:
    jobs:
      - bionic-test-setup-env
      - bionic-test-create-and-test-build:
          requires:
            - bionic-test-setup-env

  test-static-windows-build:
    jobs:
      - release-prepare-machine
      - release-windows:
          requires:
            - release-prepare-machine

  test-static-linux-build:
    jobs:
      - release-prepare-machine
      - release-linux:
          requires:
            - release-prepare-machine

  test-static-macos-build:
    jobs:
      - release-prepare-machine
      - release-macos:
          requires:
            - release-prepare-machine
